### ISSUE TITLE
[Feature Request] Select from History: copy to search box instead of executing search

### ISSUE THREAD

**Issue by SAbboushi** [bnason-nf/findallinfile#10] opened 2021-03-12 21:13 UTC
I often want to modify a previous search and would find it useful if when clicking an entry in history list, the entry populates the search box allowing me to edit it (if I want to) before pressing ENTER to execute the search.

**Comment by bnason-nf** [comment] 2021-03-12 21:53
Hi @SAbboushi,

Good to hear from you again, thanks for this good suggestion, and your previous ones.

I'm not currently aware of any way to implement this using the existing VSCode extension APIs so I'm assuming this isn't possible, but if I find something I'll update this issue. Also if you are able to find anything that might help, please let me know.

Thanks,
Benbuck

**Comment by bnason-nf** [comment] 2021-11-22 18:57
Hi @SAbboushi,

I took some time yesterday to look at this again, and I still don't think it's possible to do with the current VSCode APIs. The problem is the filtering. If you scroll through the list to select the item you want, and then we want to put that into the edit field at the top, that also acts as a filter on the list. This would be fine except that it means as soon as you scroll to the first item, if I put that into the edit field so you can modify it, the list is filtered and you can't see an of the other items, which means you can no longer scroll past the first item on the list. If you think of a way to get around this problem, please let me know, but I'm going to close this issue for now.

Thanks,
Benbuck

**Closed as completed by bnason-nf** 2021-11-22 18:57 UTC
Labels: enhancement

**Comment by SAbboushi** [comment] 2021-11-22 19:07
k thanks
